const { nanoid } = require("nanoid");

const posthtml = require('posthtml');
const minifier = require('posthtml-minifier');

const postcss = require("postcss");
const autoprefixer = require("autoprefixer");
const csso = require('csso');
const prefixer = require('postcss-prefix-selector')

const uglifyJS = require("./uglify.js");

const sources = Array.from(document.querySelectorAll(".source"));
const resultTxa = document.querySelector(".result");
const resetBtn = document.querySelector(".reset-btn");

const browserslist = ["defaults", "not dead", "last 10 versions"]
let scopeAttr = nanoid(5)

document.querySelector(".browserslist").textContent = `CSS: ${browserslist.join(", ")}`;

let comp = {}

resetBtn.addEventListener("click", () => {
    sources.forEach(source => {
        source.value = "";
    })
    resultTxa.value = "";
    comp = {}
    scopeAttr = nanoid(5)
})

sources.forEach(source => {
    source.addEventListener("input", e => {
        parseCode(source)
    })

    source.addEventListener("paste", e => {
        e.preventDefault();

        const pastedText = (e.clipboardData || window.clipboardData).getData('text');
        source.value = pastedText;

        parseCode(source)
    })
})

function parseCode(source) {
    if (source.id === "txa-html") {

        // HTML minifier

        posthtml()
            .use(minifier({
                collapseWhitespace: true,
                removeComments: true,
                includeAutoGeneratedTags: false,
                keepClosingSlash: true
            }))
            .process(source.value)
            .then(function (result) {
                const parser = new DOMParser();
                const doc = parser.parseFromString(result.html, "text/html");
                const elems = doc.querySelectorAll("*:not(html, head, body)");
                elems.forEach(elem => {
                    elem.setAttribute(`data-${scopeAttr}`, "")
                })
                const htmlStr = elems[0].outerHTML

                comp["html"] = htmlStr
                resultTxa.value = JSON.stringify(comp, null, 4);
            })
            .catch(function (error) {
                if (comp.hasOwnProperty("html")) {
                    comp["html"] = ""
                }
                resultTxa.value = JSON.stringify(comp, null, 4);
                console.error("Bullshit! Not valid HTML! 💩");
            });

    } else if (source.id === "txa-css") {

        // CSS minifier and autoprefixer

        postcss([
            autoprefixer({
                overrideBrowserslist: browserslist
            }),
            prefixer({
                prefix: scopeAttr,

                transform: function (prefix, selector, prefixedSelector, filePath, rule) {
                    return `${selector}[data-${prefix}]`;
                }
            })
        ]).process(source.value, { from: undefined }).then(result => {
            comp["css"] = csso.minify(result.css, { restructure: false }).css
            resultTxa.value = JSON.stringify(comp, null, 4);
        })
        .catch(error => {
            console.error("Bullshit! Not valid CSS! 💩");
        })

    } else if (source.id === "txa-js") {

        // JS minifier

        const result = uglifyJS.minify(source.value);
        if (!result.error) {
            comp["js"] = result.code
            resultTxa.value = JSON.stringify(comp, null, 4);
        } else {
            console.error("Bullshit! Not valid JS! 💩");
        }
    }
}

resultTxa.addEventListener("click", () => {
    navigator.clipboard.writeText(resultTxa.value);

    const span = document.createElement("span");
    span.classList.add("copied-msg");
    span.textContent = "Copied to clipboard";

    resultTxa.parentElement.appendChild(span);

    setTimeout(() => {
        resultTxa.parentElement.removeChild(span);
    }, 2000)
})
